dist: trusty
language: node_js
node_js:
  - 12

services:
  # - mongodb
  - docker

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: lheydel-github
    token:
      secure: $SONAR_TOKEN

script:
  # Build app
  - npm run build

  # Run tests
  - cd prisma && docker-compose up -d
  - npx prisma deploy
  - npm run test
  - docker-compose down && cd ..

  # Code analysis (Sonarqube)
  - sonar-scanner

git:
  depth: 3
  
notifications:
  email: false