dist: trusty
language: node_js
node_js:
  - 12

services:
  # - mongodb
  - docker

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: lheydel-github
    token:
      secure: $SONAR_TOKEN

script:
  # Build app
  - npm run build

  # Run and prepare prisma
  - cd prisma && docker-compose up -d
  - sleep 5
  - npx prisma deploy
  
  # Run tests
  - npm run test
  
  # Stop prisma
  - docker-compose down && cd ..

  # Code analysis (Sonarqube)
  - sonar-scanner

deploy:
  # Prod
  - provider: script
    script: bash ./deploy.sh prod
    skip_cleanup: true 
    on:
      branch: master
  # Test
  - provider: script
    script: bash ./deploy.sh test
    skip_cleanup: true 
    on:
      branch: test
  # Dev
  - provider: script
    script: bash ./deploy.sh dev
    skip_cleanup: true 
    on:
      branch: dev

git:
  depth: false
  
notifications:
  email: false

# Discord Webhook
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
