dist: trusty
language: node_js
node_js:
  - 12

services:
  - mongodb
  # - docker

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: lheydel-github
    token:
      secure: $SONAR_TOKEN

script:
  - npm run build
  - npm run test
  - sonar-scanner

git:
  depth: 3
  
notifications:
  email: false