version: "3"

services: 
  app:
    restart: always
    build: .
    # Override cmd in Dockerfile (here because we don't want it in prod)
    command: npm run debug
    # Override src by mounting the current directory as a volume 
    # --> code inside running container will update whenever local files are updated
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "8585:8080"
      - "5555:5555"
    links:
      - mongo
  
  # MONGO + VOLUMES --> NOT ON WINDOWS
  mongo:
    image: mongo
    # volumes: 
    #   - ./data:/data/db
    ports:
      - "27018:27017"
# volumes:
#   mongo: