version: "3"

services: 
  app:
    restart: always
    build: .
    # Override cmd in Dockerfile (here because we don't want it in prod)
    command: npm run debug
    # Override src by mounting the current directory as a volume 
    # --> code inside running container will update whenever local files are updated
    volumes:
      - .:/src
    ports:
      - "8080:8080"
      - "5858:5858"
    links:
      - prisma
      
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            uri: 'mongodb://mongo:27017'
    links:
      - mongo
  
  # MONGO + VOLUMES --> NOT ON WINDOWS
  mongo:
    image: mongo
    # volumes: 
    #   - ./data:/data/db
    ports:
      - "27018:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: prisma
    #   MONGO_INITDB_ROOT_PASSWORD: prisma
    # volumes:
    #   - mongo:/var/lib/mongo
# volumes:
#   mongo: